version: '3'
services:

  zookeeper:
    image: zookeeper:3.6
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: bitnami/kafka:2.5.0
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "15672:15672" # guest/guest

  controller:
    image: ucd-lib/krm-controller:v0
    volumes:
      - ./storage:/storage/nfs
      - ./graph:/etc/krm/graph
    ports:
      - "3000:3000"

  expire:
    image: ucd-lib/krm-expire:v0
    volumes:
      - ./storage:/storage/nfs

  router:
    image: ucd-lib/krm-router:v0
    volumes:
      - ./graph:/etc/krm/graph

  default-worker:
    image: ucd-lib/krm-worker:v0
    volumes:
      - ./storage:/storage/nfs
    environment:
      - WORKER_TYPE=default.worker

  image-worker:
    image: ucd-lib/krm-node-image-worker:v0
    volumes:
      - ./storage:/storage/nfs
    environment:
      - WORKER_TYPE=node.image.worker

  decoder-krm-interface:
    image: ucd-lib/casita-decoder-krm-interface:master

  decoder:
    image: ucd-lib/grb-decoder:master
    environment:
      - GRB_FILE=decoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ../docker.key:/root/.ssh/id_rsa
    restart: always

  secdecoder:
    image: ucd-lib/grb-decoder:master
    environment:
      - GRB_FILE=secdecoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ../docker.key:/root/.ssh/id_rsa
    restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  mongo-data:
