version: '3'
services:

  zookeeper:
    image: zookeeper:3.6
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: bitnami/kafka:2.5.0
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "5672:5672"
      - "15672:15672" # guest/guest

  decoder:
    image: ucd-lib/grb-decoder:master
    environment:
      - GRB_FILE=decoded
    volumes:
      - ../docker.key:/root/.ssh/id_rsa
    restart: always

  secdecoder:
    image: ucd-lib/grb-decoder:master
    environment:
      - GRB_FILE=secdecoded
    volumes:
      - ../docker.key:/root/.ssh/id_rsa
    restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  mongo-data:
