version: '3'
services:

  zookeeper:
    image: zookeeper:3.6
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: bitnami/kafka:2.5.0
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "15672:15672" # guest/guest

  controller:
    image: ucdlib/krm-controller:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ./graph:/etc/krm/graph
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    restart: always

  api:
    image: ucdlib/krm-api:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - API_SERVICES=ws-service:ws
    restart: always

  expire:
    image: ucdlib/krm-expire:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    restart: always

  router:
    image: ucdlib/krm-router:main
    env_file:
      - .env
    volumes:
      - ./graph:/etc/krm/graph
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    restart: always

  ws-service:
    image: ucdlib/krm-ws-service:main
    env_file:
      - .env
    restart: always

  default-worker:
    image: ucdlib/krm-worker:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=default.worker

  image-worker:
    image: ucdlib/krm-node-image-worker:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=node.image.worker

  stream-status-worker:
    image: ucdlib/krm-node-stream-status-worker:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
    environment:
      - WORKER_TYPE=node.status.worker

  decoder-krm-interface:
    image: ucdlib/casita-decoder-krm-interface:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
    restart: always

  secdecoder-krm-interface:
    image: ucdlib/casita-decoder-krm-interface:main
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
    restart: always

  decoder:
    image: ucdlib/grb-decoder:main
    env_file:
      - .env
    environment:
      - GRB_FILE=decoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ./docker.key:/root/.ssh/id_rsa
    restart: always

  secdecoder:
    image: ucdlib/grb-decoder:main
    env_file:
      - .env
    environment:
      - GRB_FILE=secdecoded
      - TARGET_URL=http://secdecoder-krm-interface:3000
    volumes:
      - ./docker.key:/root/.ssh/id_rsa
    restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  mongo-data:
  service-account:
