apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "10.128.0.26"
  selector:
    app: api-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
