apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      # 'mount' /etc/krm/setup on start
      # https://stackoverflow.com/questions/30538210/how-to-mimic-volumes-from-in-kubernetes
      initContainers:
      - name: graph-setup-init
        image: gcr.io/ucdlib-pubreg/casita-krm-graph-setup:v0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cp -r /setup/* /mnt/setup"]
        volumeMounts:
        - mountPath: /mnt/setup
          name: graph-setup-volume
      containers:
      - name: api-deployment
        image: gcr.io/ucdlib-pubreg/krm-api:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: KRM_ENV
          value: "gce-prod"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
        - mountPath: /etc/krm/setup
          name: graph-setup-volume
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      - name: graph-setup-volume
        emptyDir: {}
      - name: service-account
        secret:
          secretName: service-account
      nodeSelector:
        intendedfor: krm-services
