apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: ucdlib/krm-controller:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "k8s-local-dev"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: system
