apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-status-deployment
spec:
  selector:
    matchLabels:
      app: stream-status
  template:
    metadata:
      labels:
        app: stream-status
    replicas: 2
    spec:
      containers:
      - name: stream-status
        image: ucdlib/casita-decoder-krm-interface:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "k8s-local-dev"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: system
