apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder-krm-interface-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decoder-krm-interface
  template:
    metadata:
      labels:
        app: decoder-krm-interface
    spec:
      containers:
      - name: decoder-krm-interface
        image: ucdlib/casita-decoder-krm-interface:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: decoders
