apiVersion: apps/v1
kind: Deployment
metadata:
  name: expire-deployment
spec:
  selector:
    matchLabels:
      app: expire
  template:
    metadata:
      labels:
        app: expire
    spec:
      containers:
      - name: expire
        image: ucdlib/krm-expire:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: krm-services
