apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-payload-worker-deployment
spec:
  selector:
    matchLabels:
      app: generic-payload-worker
  template:
    metadata:
      labels:
        app: generic-payload-worker
    spec:
      containers:
      - name: generic-payload-worker
        image: ucdlib/krm-generic-payload-worker:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: WORKER_TYPE
          value: generic.payload.worker
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: worker
