apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-deployment
spec:
  selector:
    matchLabels:
      app: h2-deployment
  template:
    metadata:
      labels:
        app: h2-deployment
    spec:
      containers:
      - name: h2-deployment
        image: ucdlib/krm-http2-service:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        - name: KAFKA_HOST
          value: "kafka-service"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
      nodeSelector:
        intendedfor: krm-services
