apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-deployment
spec:
  selector:
    matchLabels:
      app: h2-deployment
  template:
    metadata:
      labels:
        app: h2-deployment
    spec:
      containers:
      - name: h2-deployment
        image: ucdlib/krm-http2-service:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "k8s-local-dev"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
      nodeSelector:
        intendedfor: system
