apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-worker-deployment
spec:
  selector:
    matchLabels:
      app: image-worker
  template:
    metadata:
      labels:
        app: image-worker
    spec:
      containers:
      - name: image-worker
        image: ucdlib/krm-node-image-worker:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "k8s-local-dev"
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: system
