# https://cloud.google.com/filestore/docs/accessing-fileshares
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-persistent-storage
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /casitakrm
    server: 10.28.186.144
