apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: ucdlib/krm-router:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
      nodeSelector:
        intendedfor: system
