apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: ucdlib/krm-router:dev
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "128Mi"
            cpu: "100m"
      nodeSelector:
        intendedfor: system
