apiVersion: apps/v1
kind: Deployment
metadata:
  name: secdecoder-deployment
spec:
  selector:
    matchLabels:
      app: secdecoder
  template:
    metadata:
      labels:
        app: secdecoder
    spec:
      containers:
      - name: secdecoder
        image: ucdlib/grb-decoder:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "k8s-local-dev"
        - name: SSH_KEY_USERNAME
          value: "jrmerz"
        - name: GRB_FILE
          value: "secdecoded"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: ssh-rsa-key
          mountPath: /root/.ssh/id_rsa
      volumes:
      - name: ssh-rsa-key
        secret:
          secretName: ssh-rsa-key
      nodeSelector:
        intendedfor: system
