apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-status-deployment
spec:
  selector:
    matchLabels:
      app: stream-status
  template:
    metadata:
      labels:
        app: stream-status
    spec:
      containers:
      - name: stream-status
        image: ucdlib/krm-node-stream-status-service:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: system
