apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-status-deployment
spec:
  selector:
    matchLabels:
      app: stream-status-deployment
  template:
    metadata:
      labels:
        app: stream-status-deployment
    spec:
      containers:
      - name: stream-status-deployment
        image: ucdlib/krm-node-stream-status-service:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: krm-services
