apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-status-worker-deployment
spec:
  selector:
    matchLabels:
      app: stream-status-worker
  template:
    metadata:
      labels:
        app: stream-status-worker
    spec:
      containers:
      - name: stream-status-worker
        image: ucdlib/krm-node-stream-status-worker:main
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "gce-prod"
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: MONGO_HOST
          value: "mongo-service"
        - name: WORKER_TYPE
          value: node.status.worker
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: worker
