apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{API_SERVICE_INTERNAL_IP}}"
  selector:
    app: api-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000