apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      # 'mount' /etc/krm/setup on start
      # https://stackoverflow.com/questions/30538210/how-to-mimic-volumes-from-in-kubernetes
      initContainers:
      - name: graph-setup-init
        image: ucdlib/casita-krm-graph-setup:v0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cp -r /setup/* /mnt/setup"]
        volumeMounts:
        - mountPath: /mnt/setup
          name: graph-setup-volume
      containers:
      - name: controller
        image: {{CONTROLLER_IMAGE_NAME}}:{{KRM_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: MONGO_HOST
          value: "mongo-service"
        - name: KAFKA_HOST
          value: "kafka-service"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      - name: graph-setup-volume
        emptyDir: {}
      nodeSelector:
        intendedfor: krm-services