apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder-krm-interface-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decoder-krm-interface
  template:
    metadata:
      labels:
        app: decoder-krm-interface
    spec:
      containers:
      - name: decoder-krm-interface
        image: {{DECORDER_KRM_INTERFACE_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: decoders