apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-worker-deployment
spec:
  selector:
    matchLabels:
      app: default-worker
  template:
    metadata:
      labels:
        app: default-worker
    spec:
      containers:
      - name: default-worker
        image: {{WORKER_IMAGE_NAME}}:{{KRM_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: WORKER_TYPE
          value: default.worker
        resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      - name: service-account
        secret:
          secretName: service-account
      nodeSelector:
        intendedfor: worker