apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-topics-worker-deployment
spec:
  selector:
    matchLabels:
      app: external-topics-worker
  template:
    metadata:
      labels:
        app: external-topics-worker
    spec:
      containers:
      - name: external-topics-worker
        image: {{EXTERNAL_TOPICS_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAFKA_HOST
          value: "kafka-service"
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: WORKER_TYPE
          value: external.topics.worker
        resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      - name: service-account
        secret:
          secretName: service-account
      nodeSelector:
        intendedfor: worker