apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-payload-worker-deployment
spec:
  selector:
    matchLabels:
      app: generic-payload-worker
  template:
    metadata:
      labels:
        app: generic-payload-worker
    spec:
      containers:
      - name: generic-payload-worker
        image: {{GENERIC_PAYLOAD_WORKER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
        volumeMounts:
        - mountPath: /storage
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: system