apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-deployment
spec:
  selector:
    matchLabels:
      app: h2-deployment
  template:
    metadata:
      labels:
        app: h2-deployment
    spec:
      containers:
      - name: h2-deployment
        image: {{HTTP2_SERVICE_IMAGE_NAME}}:{{KRM_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: KAFKA_HOST
          value: "kafka-service"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
      nodeSelector:
        intendedfor: krm-services