apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-persistent-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-persistent-storage
  resources:
    requests:
      storage: 1T