apiVersion: v1
kind: Service
metadata:
  name: open-kafka-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{OPEN_KAFKA_WS_SERVICE_INTERNAL_IP}}"
  selector:
    app: open-kafka-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000