apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  - name: admin
    port: 15672
    targetPort: 15672