apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      initContainers:
      - name: graph-setup-init
        image: {{GRAPH_SETUP_IMAGE_NAME}}:{{APP_VERSION}}
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cp -r /setup/* /mnt/setup"]
        volumeMounts:
        - mountPath: /mnt/setup
          name: graph-setup-volume
      containers:
      - name: router
        image: {{ROUTER_IMAGE_NAME}}:{{KRM_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: LOG_LEVEL
          value: "{{K8S_LOG_LEVEL}}"
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: KAFKA_HOST
          value: "kafka-service"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /etc/krm/setup
          name: graph-setup-volume
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: graph-setup-volume
        emptyDir: {}
      - name: service-account
        secret:
          secretName: service-account
      nodeSelector:
        intendedfor: krm-services