apiVersion: apps/v1
kind: Deployment
metadata:
  name: secdecoder-deployment
spec:
  selector:
    matchLabels:
      app: secdecoder
  template:
    metadata:
      labels:
        app: secdecoder
    spec:
      containers:
      - name: secdecoder
        image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        env:
        - name: GRB_FILE
          value: "secdecoded"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: ssh-rsa-key
          mountPath: /root/.ssh/id_rsa
      volumes:
      - name: ssh-rsa-key
        secret:
          secretName: ssh-rsa-key
      nodeSelector:
        intendedfor: system