apiVersion: apps/v1
kind: Deployment
metadata:
  name: secdecoder-deployment
spec:
  selector:
    matchLabels:
      app: secdecoder
  template:
    metadata:
      labels:
        app: secdecoder
    spec:
      containers:
      - name: secdecoder
        image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: SSH_KEY_USERNAME
          valueFrom:
            secretKeyRef:
              name: decoder-ssh-user
              key: ssh-username
        - name: GRB_FILE
          value: "secdecoded"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: decoder-ssh-key
          mountPath: /root/.ssh/id_rsa
      volumes:
      - name: decoder-ssh-key
        secret:
          secretName: decoder-ssh-key
      nodeSelector:
        intendedfor: decoders