apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-status-deployment
spec:
  selector:
    matchLabels:
      app: stream-status-deployment
  template:
    metadata:
      labels:
        app: stream-status-deployment
    spec:
      containers:
      - name: stream-status-deployment
        image: {{NODE_STREAM_STATUS_SERVICE_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: MONGO_HOST
          value: "mongo-service"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: nfs-persistent-storage-claim
          readOnly: false
      nodeSelector:
        intendedfor: krm-services