apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  selector:
    matchLabels:
      app: ws-deployment
  template:
    metadata:
      labels:
        app: ws-deployment
    spec:
      containers:
      - name: ws-deployment
        image: {{WS_SERVICE_IMAGE_NAME}}:{{KRM_TAG}}
        imagePullPolicy: Always
        env:
        - name: KRM_ENV
          value: "{{K8S_KRM_ENV}}"
        - name: KAFKA_HOST
          value: "kafka-service"
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
          requests:
            memory: "32Mi"
            cpu: "100m"
      nodeSelector:
        intendedfor: krm-services