version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  mongo:
    image: {{MONGO_IMAGE_NAME}}:{{MONGO_TAG}}
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: {{RABBITMQ_IMAGE_NAME}}:{{RABBITMQ_TAG}}
    ports:
      - "15672:15672" # guest/guest

  controller:
    image: {{CONTROLLER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ./graph:/etc/krm/graph
    ports:
      - "3000:3000"

  expire:
    image: {{EXPIRE_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs

  router:
    image: {{ROUTER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./graph:/etc/krm/graph

  default-worker:
    image: {{WORKER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
    environment:
      - WORKER_TYPE=default.worker

  image-worker:
    image: {{NODE_IMAGE_WORKER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
    environment:
      - WORKER_TYPE=node.image.worker

  decoder-krm-interface:
    image: {{DECORDER_KRM_INTERFACE_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env

  decoder:
    image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    environment:
      - GRB_FILE=decoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ./docker.key:/root/.ssh/id_rsa
    restart: always

  secdecoder:
    image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    environment:
      - GRB_FILE=secdecoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ./docker.key:/root/.ssh/id_rsa
    restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  mongo-data: