version: '3'
services:

  zookeeper:
    image: {{ZOOKEEPER_IMAGE_NAME}}:{{ZOOKEEPER_TAG}}
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: {{KAFKA_IMAGE_NAME}}:{{KAFKA_TAG}}
    env_file:
      - .env
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_MESSAGE_MAX_BYTES=50000000
      - KAFKA_CLIENT_USER=admin
    volumes: 
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  ksqldb:
    image: confluentinc/ksqldb-server:0.12.0
    hostname: ksqldb
    container_name: ksqldb
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092

  mongo:
    image: {{MONGO_IMAGE_NAME}}:{{MONGO_TAG}}
    volumes:
      - mongo-data:/data/db

  postgres:
    image: {{POSTGIS_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    volumes:
      - pg-data:/var/lib/postgresql/data

  rabbitmq:
    image: {{RABBITMQ_IMAGE_NAME}}:{{RABBITMQ_TAG}}
    ports:
      - "5672:5672"
      - "15672:15672" # guest/guest

  controller:
    image: {{CONTROLLER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    restart: always
    volumes:
      - ./storage:/storage/nfs
      - ../setup:/etc/krm/setup
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/controller/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/controller/lib:/service/lib
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
  # command: bash -c 'tail -f /dev/null'

  api:
    image: {{API_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ../setup:/etc/krm/setup
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/api/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/api/controllers:/service/controllers
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/api/lib:/service/lib
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    ports:
      - "${HOST_PORT:-3000}:3000"
    # command: bash -c 'tail -f /dev/null'

  expire:
    image: {{EXPIRE_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/expire/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    # command: bash -c 'tail -f /dev/null'

  router:
    image: {{ROUTER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    restart: always
    volumes:
      - ../setup:/etc/krm/setup
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/router/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
  # command: bash -c 'tail -f /dev/null'

  ws-service:
    image: {{WS_SERVICE_IMAGE_NAME}}:{{KRM_TAG}}
    volumes:
      - ../setup:/etc/krm/setup
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/public-events/ws/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    env_file:
      - .env
  # command: bash -c 'tail -f /dev/null'

  h2-service:
    image: {{HTTP2_SERVICE_IMAGE_NAME}}:{{KRM_TAG}}
    volumes:
      - ../setup:/etc/krm/setup
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/public-events/http2/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    env_file:
      - .env
    ports:
      - "${H2_EVENT_PORT:-3001}:3000"
    # command: bash -c 'tail -f /dev/null'

  default-worker:
    image: {{WORKER_IMAGE_NAME}}:{{KRM_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/worker/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{KRM_REPO_NAME}}/worker/lib:/service/lib
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=default.worker
  # command: bash -c 'tail -f /dev/null'

  image-worker:
    image: {{NODE_IMAGE_WORKER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/node-image-utils/index.js:/command/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/node-image-utils/lib:/command/lib
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=node.image.worker
    # command: bash -c 'tail -f /dev/null'

  generic-payload-worker:
    image: {{GENERIC_PAYLOAD_WORKER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/generic-payload-parser/index.js:/command/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/generic-payload-parser/lib:/command/lib
    environment:
      - WORKER_TYPE=generic.payload.worker
    # command: bash -c 'tail -f /dev/null'

  stream-status-worker:
    image: {{NODE_STREAM_STATUS_WORKER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/status/worker/index.js:/command/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/status/worker/lib:/command/lib
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=node.status.worker
    # command: bash -c 'tail -f /dev/null'

  ring-buffer-worker:
    image: {{RING_BUFFER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/index.js:/command/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/lib:/command/lib
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/test:/command/test
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    environment:
      - WORKER_TYPE=ring.buffer.worker
    command: bash -c 'tail -f /dev/null'

  ring-buffer-service:
    image: {{RING_BUFFER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/index.js:/command/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/service.js:/command/service.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/lib:/command/lib
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/block-ring-buffer/test:/command/test
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    command: bash -c 'tail -f /dev/null'

  stream-status-service:
    image: {{NODE_STREAM_STATUS_SERVICE_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/status/service/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    command: bash -c 'tail -f /dev/null'

  decoder:
    image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    environment:
      - GRB_FILE=secdecoded
      - TARGET_URL=http://decoder-krm-interface:3000
    volumes:
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/decoder/index.js:/service/index.js
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/decoder/test.js:/service/test.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
      - ../docker.key:/root/.ssh/id_rsa
      - ./testsecdecorded.dat:/service/testsecdecorded.dat
    restart: always
    command: bash -c 'tail -f /dev/null'

  decoder-krm-interface:
    image: {{DECORDER_KRM_INTERFACE_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
    env_file:
      - .env
    restart: always
    volumes:
      - ./storage:/storage/nfs
      - ../{{REPOSITORY_DIR}}/{{CASITA_TASKS_REPO_NAME}}/decoder-krm-interface/index.js:/service/index.js
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/google/service-account.json
    # command: bash -c 'tail -f /dev/null'

  # secdecoder:
  #   image: {{GRB_DECORDER_IMAGE_NAME}}:{{CASITA_TASKS_TAG}}
  #   environment:
  #     - GRB_FILE=secdecoded
  #   volumes:
  #     - ../docker.key:/root/.ssh/id_rsa
  #   restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  mongo-data:
  service-account:
  pg-data: